# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - develop

pool:
  vmImage: ubuntu-latest

variables:
- name: kvnm
  value: 'kv-dev-eastus2-cdp'
- name: kvrg
  value: 'rg-dev-eastus2-base'
- name: sp
  value: 'cxi-devops'


steps:

- task: DownloadPipelineArtifact@2
  inputs:
    source: 'current' 
    runBranch: 'refs/heads/master' 
    path: '$(Pipeline.Workspace)' 

- task: AzureCLI@2
  displayName: Adding dynamic IP to Azure Keyvault
  inputs:
    azureSubscription: $(sp)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      ip=$(host myip.opendns.com resolver1.opendns.com | grep 'myip' | awk '{print $4}')
      echo Adding $ip into firewall rules
      az keyvault network-rule add -n $(kvnm) -g $(kvrg) --ip-address $ip

- task: AzureKeyVault@2
  inputs:
    azureSubscription: $(sp)
    KeyVaultName: $(kvnm)
    SecretsFilter: 'databricks-workspace-token'
    RunAsPreJob: false

- task: AzureCLI@2
  displayName: Removing dynamic IP from Azure Keyvault
  inputs:
    azureSubscription: $(sp)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      ip=$(host myip.opendns.com resolver1.opendns.com | grep 'myip' | awk '{print $4}')
      echo Removing $ip from firewall rules
      az keyvault network-rule remove -n $(kvnm) -g $(kvrg) --ip-address $ip/32

- task: configuredatabricks@0
  inputs:
    url: 'https://adb-8464693284532204.4.azuredatabricks.net/'
    token: '$(databricks-workspace-token)'

- task: deploynotebooks@0
  inputs:
    notebooksFolderPath: '$(Pipeline.Workspace)/s/datalake'
    workspaceFolder: '/datalake'