# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
- name: kvnm
  value: 'kvdeveastus2cxizrjtbfjlf'
- name: kvrg
  value: 'rg-dev-eastus2-network'

steps:

- task: DownloadPipelineArtifact@2
  inputs:
    source: 'current' 
    # Options: current, specific
    #project: # Required when source == Specific
    #pipeline: # Required when source == Specific
    #preferTriggeringPipeline: false # Optional
    #runVersion: 'latest' # Required when source == Specific# Options: latest, latestFromBranch, specific
    runBranch: 'refs/heads/master' # Required when source == Specific && RunVersion == LatestFromBranch
    #runId: # Required when source == Specific && RunVersion == Specific
    #tags: # Optional
    #artifact: # Optional
    #patterns: '**' # Optional
    path: '$(Pipeline.Workspace)' 

- script: |
    ip=$(host myip.opendns.com resolver1.opendns.com | grep 'myip' | awk '{print $4}')

    if [  -z "$ip" ] 
    then 
    	az keyvault network-rule add -n $(kvnm) -g $(kvrg) --ip-address $ip 
    else 
	    exit 1
    fi
  displayName: 'Adding dynamic IP to Azure Keyvault'
