# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
- name: kvnm
  value: 'kvdeveastus2cxizrjtbfjlf'
- name: kvrg
  value: 'rg-dev-eastus2-network'

steps:

- script: |
  ip=$(host myip.opendns.com resolver1.opendns.com | grep 'myip' | awk '{print $4}')
  if [  -z "$ip" ] 
  then 
    az keyvault network-rule add -n $(kvnm) -g $(kvrg) --ip-address $ip 
  else 
    exit 1
  fi
  displayName: 'Adding dynamic IP to Azure Keyvault'
