trigger:
  branches:
    include:
    - develop

pool:
  vmImage: ubuntu-18.04

stages:
- stage: develop
  jobs:  
   - job: develop
     steps:
       
       - task: UsePythonVersion@0
         inputs:
           versionSpec: '3.8.*'
           addToPath: true
           architecture: 'x64'
       - script: |
          pip install pytest requests setuptools wheel
          pip install -U databricks-connect==8.1.*
         displayName: 'Load Python Dependencies'
       - task: Bash@3
         displayName: Other dependencies
         inputs:
           targetType: 'inline'
           script: |
             python -m venv .venv &&
             sbt setupDatabricksConnect
       - task: Bash@3
         displayName: sbt assembly
         inputs:
            targetType: 'inline'
            script: 'sbt assembly'
       - task: PublishBuildArtifacts@1
         inputs:
           PathtoPublish: 'target/scala-*/*.jar'
           ArtifactName: 'cxi_cdp_data_processing_assembly'
           publishLocation: 'Container'

  
