trigger:
  branches:
    include:
    - develop

pool:
  vmImage: ubuntu-latest

stages:
- stage: develop
  jobs:  
   - job: develop
     steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'sbt assembly'

  
