trigger:
  branches:
    include:
    - develop

pool:
  vmImage: ubuntu-latest

stages:
- stage: develop
  jobs:  
   - job: develop
     steps:
       - task: installscalatools@0
         inputs:
           failOnStderr: true

  
