trigger:
  branches:
    include:
    - develop

stages:
- stage: develop
  pool: ubuntu-18.04
  jobs:  
   - job: develop
     steps:
       
       - task: UsePythonVersion@0
         inputs:
           versionSpec: '3.8.*'
           addToPath: true
           architecture: 'x64'
       - script: |
          pip install pytest requests setuptools wheel
         displayName: 'Load Python Dependencies'
       - task: Bash@3
         displayName: Other dependencies
         inputs:
           targetType: 'inline'
           script: |
             python -m venv .venv &&
             sbt setupDatabricksConnect
       - task: Bash@3
         displayName: sbt assembly
         inputs:
            targetType: 'inline'
            script: 'sbt assembly'
       - task: PublishBuildArtifacts@1
         displayName:  publish artifacts
         inputs:
           PathtoPublish: 'target/scala-2.12/cxi_cdp_data_processing_assembly_2_12.jar'
           ArtifactName: 'cxi_cdp_data_processing_assembly'
           publishLocation: 'Container'

- stage: deploy
  pool: windows-latest
  jobs:
    - job: deploy 
      steps:
       - task: databricksDeployDBFSFilesTask@0
         inputs:
            authMethod: 'bearer'
            bearerToken: 'dapib052719ada09e12daf18f1810323d1c7-2'
            region: 'eastus2'
            LocalRootFolder: 'target/scala-2.12'
            FilePattern: '*.jar'
            TargetLocation: '/FileStore/jars/cxi/'