trigger:
  branches:
    include:
    - develop

variables:
- group: cxi-cdp-data-processing
- name: version.MajorMinor
  value: '1.1' # Manually adjust the version number as needed for semantic versioning. Revision is auto-incremented.
- name: version.Revision
  value: $[counter(variables['version.MajorMinor'], 0)]
- name: version.Patсh
  value: $[counter(variables['build.reason'], 0)]
- name: versionNumber
  value: $[format('{0}.{1}', variables['version.MajorMinor'], variables['version.Patсh'])]


name: $(versionNumber)

stages:
- stage: Build
  pool:
     vmimage: ubuntu-latest
  jobs:
    - job: run_tests_and_build
      steps:
       - task: UsePythonVersion@0
         inputs:
           versionSpec: '3.8.*'
           addToPath: true
           architecture: 'x64'

       - task: AzureCLI@2
         displayName: opening firewall
         inputs:
           azureSubscription: 'cxi-devops'
           scriptType: 'bash'
           scriptLocation: 'inlineScript'
           inlineScript: |
                       IPADDR=$(dig +short "myip.opendns.com" "@resolver1.opendns.com")
                       echo "Opening firewall: $IPADDR"
                       az keyvault network-rule add --name kv-dev-eastus2-cdp --ip-address $IPADDR
                       az keyvault network-rule wait --name kv-dev-eastus2-cdp --updated

           failOnStandardError: true

       - task: Bash@3
         enabled: true
         displayName: Install Databricks-Connect
         inputs:
           targetType: 'inline'
           script: |
             python -m venv .venv &&
             sbt setupDatabricksConnect

       - task: AzureKeyVault@2
         displayName: Get Databricks workspace secret token
         name: get_databricks_secret_token
         inputs:
            azureSubscription: 'cxi-devops'
            KeyVaultName: 'kv-dev-eastus2-cdp'
            SecretsFilter: 'cxi-int-dbws-workspaceToken'
            RunAsPreJob: false

       - task: configuredatabricks@0
         enabled: true
         inputs:
           url: $(WORKSPACE-REGION-URL)
           token: $(cxi-int-dbws-workspaceToken)

       - script: |
          source .venv/bin/activate
          echo "y
              $(WORKSPACE-REGION-URL)
              $(cxi-int-dbws-workspaceToken)
              $(EXISTING-CLUSTER-ID)
              $(WORKSPACE-ORG-ID)
              $(DATABRICKS-PORT)" | databricks-connect configure
          databricks-connect test
         displayName: 'Configure databricks-connect'
         enabled: true

       - task: Bash@3
         displayName: Execute tests
         inputs:
           targetType: 'inline'
           script: 'sbt jacoco'

       - task: PublishTestResults@2
         displayName: publish tests result
         inputs:
           testResultsFormat: 'JUnit'
           testResultsFiles: '**/target/test-reports/*.xml'
           searchFolder: '$(Build.SourcesDirectory)'
           mergeTestResults: true
           testRunTitle: 'JUnit'

       - task: PublishCodeCoverageResults@1
         displayName: publish JaCoCo code coverage results
         inputs:
           codeCoverageTool: 'JaCoCo'
           summaryFileLocation: '**/target/scala-2.12/jacoco/report/*.xml'
           reportDirectory: '**/target/scala-2.12/jacoco/report/html/'
           failIfCoverageEmpty: true

       - task: PublishBuildArtifacts@1
         displayName: publish artifacts
         enabled: true
         inputs:
           PathtoPublish: 'target/scala-2.12/cxi_cdp_data_processing_assembly_2_12.jar'
           ArtifactName: 'cxi_cdp_data_processing_assembly'
           publishLocation: 'Container'

       - task: AzureCLI@2
         displayName: closing firewall
         condition: always()
         inputs:
           azureSubscription: 'cxi-devops'
           scriptType: 'bash'
           scriptLocation: 'inlineScript'
           inlineScript: |
                       IPADDR=$(dig +short "myip.opendns.com" "@resolver1.opendns.com")
                       echo "Closing firewall: $IPADDR"
                       az keyvault network-rule remove --name kv-dev-eastus2-cdp --ip-address $IPADDR

           failOnStandardError: true

- stage: Sonar_Qube
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  pool: self
  jobs:
      - job:
        steps:
          - task: SonarQubePrepare@4
            enabled: true
            inputs:
              SonarQube: 'sonar'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'cxi-cdp-data-processing'
              cliSources: '.'
          - task: SonarQubeAnalyze@4
            enabled: true
          - task: SonarQubePublish@5
            inputs:
              pollingTimeoutSec: '300'
